const UiActionTypes = {
  LEFT_MENU_TOGGLE: 'LEFT_MENU_TOGGLE',
  CLOSE_HEADER_MENU: 'CLOSE_HEADER_MENU',
  TOGGLE_HEADER_MENU: 'TOGGLE_HEADER_MENU',
  SHOW_CUSTOM_POPUP: 'SHOW_CUSTOM_POPUP',
  CLOSE_CUSTOM_POPUP: 'CLOSE_CUSTOM_POPUP',
}

export default UiActionTypes
