const PaymentActionTypes = {
  GET_DATA_START: 'GET_DATA_START',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_FAILURE: 'GET_DATA_FAILURE',

  GET_SINGLE_ITEM_START: 'GET_SINGLE_ITEM_START',
  GET_SINGLE_ITEM_SUCCESS: 'GET_SINGLE_ITEM_SUCCESS',
  GET_SINGLE_ITEM_FAILURE: 'GET_SINGLE_ITEM_FAILURE',

  SET_CURRENT_ITEM: 'SET_CURRENT_ITEM'
}

export default PaymentActionTypes
